### ISSUE TITLE
Finish documenting installation steps

### ISSUE THREAD

**Issue by eliasgruenewald** [PrivacyEngineering/tira#1]
I just started to document the installation steps. Could you add the remaining steps for correctly setting the credentials? I tried to reverse engineer some stuff already. :-) Thanks!

See also https://github.com/PrivacyEngineering/tira/tree/feature/installation#installation.

**Comment by olegsfinest** [comment]
Will do! This works with the Rails encrypted credentials: https://edgeguides.rubyonrails.org/security.html#custom-credentials

I will provide the steps necessary for deploying and developing and an example credential configuration template.

**Comment by eliasgruenewald** [comment]
Excellent!
